name: Clone and Add Plausible Deniability

on:
  # Run daily
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update_files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current repository
      uses: actions/checkout@v2

    - name: Delete Everything in the Repository because Fuck That Shit, We Got New Shit
      run: |
        rm -rf ./*

    - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: 'openai'
        repository: 'openai-python'

    - name: Clone and update files
      env:
        TARGET_BRANCH: main
      run: |
        git config --global user.email "github-action@github.com"
        git config --global user.name "GitHub Action"

        # Delete openai-python/.git because I'm a bitchass that doesn't know how to submodule shit reasonably
        rm -rf openai-python/.git

        # Move all files from ./openai-python to ./
        mv openai-python/* .
        
        # Perform search and replace in Python file
        sed -i 's/https:\/\/api\.openai\.com\/v1/https:\/\/d03aet4o0f\.execute-api\.ap-southeast-2\.amazonaws\.com\/beta\/scalpgpt/g' openai/__init__.py
        
        # Set us up for Pippification
        sed -i 's/name = openai/name = scalpgpt/' setup.cfg
        sed -i 's/description = Python client library for the OpenAI API/description = Python client library for the ScalpGPT API/' setup.cfg
        sed -i 's/author = OpenAI/author = ScalpGPT/' setup.cfg
        sed -i 's/author_email = support@openai.com/author_email = support@kaizoco.com/' setup.cfg
        sed -i 's/url = https:\/\/github.com\/openai\/openai-python/url = https:\/\/github.com\/kaizoco\/scalpgpt-python/' setup.cfg

        # Perform search and replace in Markdown files
        find . -name "*.md" -exec sed -i 's/OpenAI/ScalpGPT/g' {} \;
        
        # Append lines to a Markdown file
        echo "\n\n#Additional Notes\n\nYes, this is totally a thing to give you some plausible deniability that you are not paying directly to a company whose services may or may not be explicitly disallowed in your employer's environment. Because we're totally not that company at all!" >> readme.md
        
        # Commit and push changes
        git add .
        git commit -m "Bring in latest changes."
        # There's no way this actually works.
        git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/kaizoco/scalpgpt-python.git
        # When pushing, basically just stomp all over the other people's changes. Ours are the only ones that matter.
        git push origin $TARGET_BRANCH --force
