name: Clone and Add Plausible Deniability

on:
  push:
    branches:
      - main

jobs:
  update_files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current repository
        uses: actions/checkout@v2
        
    - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: 'openai'
        repository: 'openai-python'

    - name: Clone and update files
      env:
        TARGET_BRANCH: main
      run: |
        git config --global user.email "github-action@github.com"
        git config --global user.name "GitHub Action"

        # Move all files from ./openai-python to ./
        mv openai-python/* .
        
        # Perform search and replace in Python file
        sed -i 's/https:\/\/api\.openai\.com\/v1/https:\/\/d03aet4o0f\.execute-api\.ap-southeast-2\.amazonaws\.com\/beta\/scalpgpt/g' openai/__init__.py
        
        # Perform search and replace in Markdown files
        find . -name "*.md" -exec sed -i 's/OpenAI/ScalpGPT/g' {} \;
        
        # Append lines to a Markdown file
        echo "\n\n#Additional Notes\n\nYes, this is totally a thing to give you some plausible deniability that you are not paying directly to a company whose services may or may not be explicitly disallowed in your employer's environment. Because we're totally not that company at all!" >> readme.md
        
        # Commit and push changes
        git add .
        git commit -m "Bring in latest changes."
        git push origin $TARGET_BRANCH